repos:
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.19
    hooks:
      - id: isort
  - repo: https://github.com/ambv/black
    rev: stable
    hooks:
      - id: black
        language_version: python3.7
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.701
    hooks:
      - id: mypy
  - repo: https://github.com/PyCQA/bandit
    rev: '1.6.0'
    hooks:
      - id: bandit
        args: [--configfile, .bandit.yml]
  - repo: https://github.com/PyCQA/flake8
    rev: '3.7.7'
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-bugbear
  - repo: git://github.com/chewse/pre-commit-mirrors-pydocstyle
    sha: v2.1.1
    hooks:
      - id: pydocstyle
