repos:
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.4
    hooks:
      - id: isort
  - repo: https://github.com/ambv/black
    rev: stable
    hooks:
      - id: black
        language_version: python3.7
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.650
    hooks:
      - id: mypy
  - repo: https://github.com/PyCQA/bandit
    rev: d2374482dd0311e4477896ba8a338f670ad49e3f
    hooks:
      - id: bandit
        args: [--configfile, .bandit.yml]
  - repo: https://github.com/PyCQA/flake8
    rev: 9a9237a3386acb4a28b3eeb237e24cce973f17f6
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-bugbear
  - repo: git://github.com/chewse/pre-commit-mirrors-pydocstyle
    sha: v2.1.1
    hooks:
      - id: pydocstyle
